"""empty message

Revision ID: 04952f65cb72
Revises: 42c8c0776233
Create Date: 2023-11-08 23:11:34.753546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04952f65cb72'
down_revision = '42c8c0776233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
